---
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: saixos
      url-base: https://github.com/nmunnich
  projects:
    - name: zmk
      remote: saixos
      # revision: rp2040zero
      revision: dfae0777
      import: app/west.yml
  self:
    path: config
